language: cpp
cache: ccache

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
  brew:
    packages:
      - ccache

matrix:
  include:
    # - os: linux
    #   dist: bionic
    #   compiler: gcc

    # - os: linux
    #   dist: bionic
    #   compiler: clang

    - os: osx
      osx_image: xcode11
      env: OSX=10.14
      compiler: gcc
      
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ x`brew list | fgrep bash` != x'bash' ]; then brew install bash; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [ x`brew list | fgrep gcc` != x'gcc' ]; then brew install gcc; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite gcc; fi
  - git clone https://github.com/coin-or/coinbrew
  - cd coinbrew
  - mkdir $PWD/buildipopt
  - mkdir $HOME/build/coin-or/SHOT/ThirdParty/Ipopt
  - bash ./coinbrew build Ipopt:stable/3.13 --prefix=$HOME/build/coin-or/SHOT/ThirdParty/Ipopt --no-prompt --tests none --verbosity=5 --parallel-jobs=5 --build-dir=$PWD/buildipopt
  - bash ./coinbrew install Ipopt --debug
  - mkdir $PWD/buildcbc
  - mkdir $HOME/build/coin-or/SHOT/ThirdParty/Cbc
  - bash ./coinbrew build Cbc:stable/2.10 --prefix=$HOME/build/coin-or/SHOT/ThirdParty/Cbc --no-prompt --tests none --verbosity=5   --build-dir=$PWD/buildcbc
  - bash ./coinbrew install Cbc --debug
  - mkdir $HOME/build/coin-or/SHOT/build
  - cd $HOME/build/coin-or/SHOT/build
  - cmake .. -DHAS_CBC=on -DCBC_DIR=$HOME/build/coin-or/SHOT/ThirdParty/Cbc -DHAS_IPOPT=on -DIPOPT_DIR=$HOME/build/coin-or/SHOT/ThirdParty/Ipopt -DHAS_GAMS=off -DHAS_CPLEX=off -DHAS_GUROBI=off -DCOMPILE_TESTS=on

script:
  - make -j5
  - make test

after_script: